version: '3.3'

services:
  sqlDb:
    image: mysql:latest
    container_name: sql-vanilla-twitter
    environment:
      - MYSQL_USER=dhruva
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    restart: always


  vanillaTwitter:
    image: dhruvamist/vanilla-twitter-aws
    container_name: vanilla-twitter-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    restart: always

    depends_on:
      - sqlDb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-vanilla-twitter:3306/mysqlDB
      SPRING_DATASOURCE_USERNAME: dhruva
      SPRING_DATASOURCE_PASSWORD: root